steps:
  - bash: |
        echo "Hello"
        echo "This is test run"
        ls
        pwd
        testVar1=$[variables.TEST_VAR]
        echo "this is ${testVar11}"
        /bin/bash vhdbuilder/scripts/bump.sh
        