pool:
  vmImage: ubuntu-latest

steps:
- bash: |
        echo "Starting pipeline"
        echo "This is a test run"
        ls
        pwd
        token=$GITHUB_PAT
        version=$IMAGE_VERSION
        echo $token
        echo $version
        /bin/bash vhdbuilder/scripts/automate.sh $version $token
  displayName: 'Image verison bumping'
- bash: |
        echo "next stage for release notes"
        token=$GITHUB_PAT
        version=$IMAGE_VERSION
        echo $token
        echo $version
        az extension add -n azure-devops
        az devops configure --defaults organization=https://dev.azure.com/msazure project=CloudNativeCompute
        go run vhdbuilder/release-notes/autonotes/main.go --build 48161034
        git status
  displayName: 'Release Notes'