pool:
  vmImage: ubuntu-latest

steps:
- bash: |
        echo "Starting pipeline"
        echo "This is a test run"
        ls
        pwd
        token=$GITHUB_PAT
        version=$IMAGE_VERSION
        echo $token
        echo $version
        #/bin/bash vhdbuilder/scripts/automate.sh 
  displayName: 'test pipeline setup'
