name: $(Date:yyyyMMdd)$(Rev:.r)_e2e

variables:
- group: ab-e2e

pool:
  vmImage: ubuntu-18.04

jobs:
- job: E2E
  steps:
  - bash: |
      az login --service-principal -u $(AZURE_CLIENT_ID) -p $(AZURE_CLIENT_SECRET) --tenant $(AZURE_TENANT_ID)
      az account set -s $(AZURE_SUBSCRIPTION_ID)
    displayName: az login
  - bash: bash .pipelines/scripts/setup_go.sh
    displayName: setup go
  - bash: |
      go version
      #cd e2e
      #bash ./e2e-script.sh
    displayName: run e2e
  - bash: |
      #az vmss delete -g $(jq -r .group e2e/vmss.json) -n $(jq -r .vmss e2e/vmss.json)
    displayName: delete vmss
    condition: always()

- job: Matrix
  strategy:
    matrix:
      scenario_fips:
        SCENARIO_NAME: 'fips'
      scenario_gpu:
        SCENARIO_NAME: 'gpu'
      scenario_vanilla:
        SCENARIO_NAME: 'vanilla'
    maxParallel: 3
  steps:
  - bash: |
      echo "Hello from the parallel side"  